title: Mayer Real Estate
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.75
  lightness: 0.7168459
  brandStrength: 1
  brandColors:
    - '#e8e8e8'
    - '#000000'
    - '#363636'
    - '#aaaaaa'
    - '#7c7c7c'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Mayer Real Estate
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.37863
layout_spectrum: 1
