name: Mayer Real Estate
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37863
title: Mayer Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e8e8'
    - '#000000'
    - '#363636'
    - '#aaaaaa'
    - '#7c7c7c'
  brandStrength: 0
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
